language: groovy
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script:
  - ./gradlew clean build

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE TABLE animals (id MEDIUMINT NOT NULL AUTO_INCREMENT,name CHAR(30) NOT NULL,age int NOT NULL,PRIMARY KEY (id));" -uroot

after_success:
  - ./gradlew cobertura coveralls