language: groovy
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script:
  - ./gradlew clean build

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

after_success:
  - ./gradlew cobertura coveralls